# Generated by Django 3.0.7 on 2023-05-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230529_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='phot',
            new_name='photo',
        ),
    ]
